"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Users } from "lucide-react";
import { toast } from "sonner";
import { kullaniciHesabiOlustur, kullaniciParolasiniYenile, kullaniciRolleriniGuncelle } from "@/lib/actions/kullanici-yonetim";
import { toggleKullaniciAktif } from "@/lib/actions/tanimlar";
import { parolaGecerli } from "@/lib/dogrulama";
import { AktifButon, AktifRozet, BosDurum, TanimBaslik, TanimSatir } from "./tanim-ortak";

export interface KullaniciSatir { id: string; ad: string; telefon: string; rol: string; aktif: boolean; eposta?: string; rolIds?: string[] }
export interface RolSecenek { id: string; ad: string }

export function KullaniciTanim({ kullanicilar, roller = [] }: { kullanicilar: KullaniciSatir[]; roller?: RolSecenek[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [formAcik, setFormAcik] = useState(false); const [parolaIcin, setParolaIcin] = useState<KullaniciSatir | null>(null); const [rollerIcin, setRollerIcin] = useState<KullaniciSatir | null>(null);
  const [ad, setAd] = useState(""); const [eposta, setEposta] = useState(""); const [parola, setParola] = useState(""); const [telefon, setTelefon] = useState(""); const [rolIds, setRolIds] = useState<string[]>([]);
  const toggle = (id: string) => setRolIds((onceki) => onceki.includes(id) ? onceki.filter((deger) => deger !== id) : [...onceki, id]);
  const kaydet = () => startTransition(async () => { const sonuc = await kullaniciHesabiOlustur({ ad, eposta, parola, telefon, rolIds }); if (sonuc.ok) { toast.success("Kullanıcı oluşturuldu"); setFormAcik(false); setAd(""); setEposta(""); setParola(""); setTelefon(""); setRolIds([]); router.refresh(); } else toast.error(sonuc.hata ?? "Kaydedilemedi"); });
  const parolaYenile = () => startTransition(async () => { if (!parolaIcin) return; const sonuc = await kullaniciParolasiniYenile(parolaIcin.id, parola); if (sonuc.ok) { toast.success("Parola yenilendi; kullanıcının oturumları sonlandırıldı."); setParolaIcin(null); setParola(""); } else toast.error(sonuc.hata ?? "Parola yenilenemedi"); });
  const rolleriGuncelle = () => startTransition(async () => { if (!rollerIcin) return; const sonuc = await kullaniciRolleriniGuncelle(rollerIcin.id, rolIds); if (sonuc.ok) { toast.success("Kullanıcı yetkileri güncellendi"); setRollerIcin(null); setRolIds([]); router.refresh(); } else toast.error(sonuc.hata ?? "Yetkiler güncellenemedi"); });

  return <div><TanimBaslik ikon={Users} baslik="Kullanıcılar" adet={kullanicilar.length} onYeni={() => setFormAcik(true)}/>{kullanicilar.length ? <div className="space-y-2">{kullanicilar.map((kullanici) => <TanimSatir key={kullanici.id}><div><b>{kullanici.ad}</b><div className="text-xs text-sky-100">{kullanici.eposta || kullanici.telefon || "—"}</div><div className="mt-1 text-[11px] text-[var(--primary)]">{roller.filter((rol) => (kullanici.rolIds ?? []).includes(rol.id)).map((rol) => rol.ad).join(", ") || kullanici.rol}</div></div><div className="flex flex-wrap gap-2"><AktifRozet aktif={kullanici.aktif}/><button type="button" className="rounded border px-2 text-xs" onClick={() => { setRolIds(kullanici.rolIds ?? []); setRollerIcin(kullanici); }}>Yetkileri düzenle</button><button type="button" className="rounded border px-2 text-xs" onClick={() => { setParola(""); setParolaIcin(kullanici); }}>Parola yenile</button><AktifButon aktif={kullanici.aktif} disabled={pending} onClick={() => startTransition(async () => { const sonuc = await toggleKullaniciAktif(kullanici.id); if (sonuc.ok) router.refresh(); else toast.error(sonuc.hata ?? "İşlem başarısız"); })}/></div></TanimSatir>)}</div> : <BosDurum mesaj="Henüz kullanıcı tanımlı değil"/>}{formAcik && <KullaniciForm ad={ad} eposta={eposta} parola={parola} telefon={telefon} roller={roller} rolIds={rolIds} pending={pending} onKapat={() => setFormAcik(false)} onAd={setAd} onEposta={setEposta} onParola={setParola} onTelefon={setTelefon} onToggle={toggle} onKaydet={kaydet}/>} {rollerIcin && <RolDuzenlemeForm kullanici={rollerIcin} roller={roller} rolIds={rolIds} pending={pending} onKapat={() => { setRollerIcin(null); setRolIds([]); }} onToggle={toggle} onKaydet={rolleriGuncelle}/>} {parolaIcin && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><section className="w-full max-w-md rounded-xl bg-[var(--surface)] p-5"><button type="button" className="float-right" onClick={() => setParolaIcin(null)}>Kapat</button><h2 className="text-lg font-extrabold">{parolaIcin.ad} parolasını yenile</h2><p className="mt-2 text-sm">Yeni parola kaydedildiğinde kullanıcının açık oturumları güvenlik için kapatılır.</p><input className="saha-input mt-4 w-full" type="password" placeholder="Yeni parola (en az 6 karakter, harf ve rakam)" value={parola} onChange={(event) => setParola(event.target.value)}/><button type="button" disabled={pending || !parolaGecerli(parola)} onClick={parolaYenile} className="saha-btn mt-3 w-full bg-[var(--primary)] text-white">Parolayı yenile</button></section></div>}</div>;
}

function RolDuzenlemeForm({ kullanici, roller, rolIds, pending, onKapat, onToggle, onKaydet }: { kullanici: KullaniciSatir; roller: RolSecenek[]; rolIds: string[]; pending: boolean; onKapat: () => void; onToggle: (id: string) => void; onKaydet: () => void }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><section className="w-full max-w-md rounded-xl bg-[var(--surface)] p-5"><button type="button" className="float-right" onClick={onKapat}>Kapat</button><h2 className="text-lg font-extrabold">{kullanici.ad} yetkileri</h2><p className="mt-2 text-sm">Kullanıcının erişebileceği modül ve işlemler seçilen yetki gruplarından gelir.</p><div className="mt-4 space-y-2">{roller.map((rol) => <label key={rol.id} className="flex gap-2 text-sm"><input type="checkbox" checked={rolIds.includes(rol.id)} onChange={() => onToggle(rol.id)}/>{rol.ad}</label>)}</div><button type="button" disabled={pending || !rolIds.length} onClick={onKaydet} className="saha-btn mt-5 w-full bg-[var(--primary)] text-white">Yetkileri kaydet</button></section></div>;
}

function KullaniciForm({ ad, eposta, parola, telefon, roller, rolIds, pending, onKapat, onAd, onEposta, onParola, onTelefon, onToggle, onKaydet }: { ad: string; eposta: string; parola: string; telefon: string; roller: RolSecenek[]; rolIds: string[]; pending: boolean; onKapat: () => void; onAd: (v: string) => void; onEposta: (v: string) => void; onParola: (v: string) => void; onTelefon: (v: string) => void; onToggle: (id: string) => void; onKaydet: () => void }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><section className="w-full max-w-md rounded-xl bg-[var(--surface)] p-5"><button type="button" className="float-right" onClick={onKapat}>Kapat</button><h2 className="text-lg font-extrabold">Yeni kullanıcı hesabı</h2><div className="mt-4 space-y-3"><input className="saha-input w-full" placeholder="Ad soyad" value={ad} onChange={(event) => onAd(event.target.value)}/><input className="saha-input w-full" placeholder="E-posta" type="email" value={eposta} onChange={(event) => onEposta(event.target.value)}/><input className="saha-input w-full" placeholder="Parola (en az 6 karakter, harf ve rakam)" type="password" value={parola} onChange={(event) => onParola(event.target.value)}/><input className="saha-input w-full" placeholder="Telefon" value={telefon} onChange={(event) => onTelefon(event.target.value)}/><div><b className="text-sm">Yetki grupları</b>{roller.map((rol) => <label key={rol.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={rolIds.includes(rol.id)} onChange={() => onToggle(rol.id)}/>{rol.ad}</label>)}</div><button type="button" disabled={pending || !ad || !eposta || !parolaGecerli(parola) || !rolIds.length} onClick={onKaydet} className="saha-btn w-full bg-[var(--primary)] text-white">Kullanıcı oluştur</button></div></section></div>;
}
